version: "3"
services:
    backend:
        build: ./backend
        restart: on-failure
        environment:
            - PORT=:3000
            - DB_HOST=database
            - DB_PORT=26257
            - DB_USER=root
            - DB_NAME=postgres
            - DB_PASSWORD=""
        volumes:
            - ./static/:/server/static/
        depends_on:
            - database
        links:
            - database
        ports:
            - "3000:3000"
    frontend:
        build: ./frontend
        environment:
            - API_URL=http://backend:3000
            - PORT=4000
        depends_on:
            - backend
        ports:
            - "4000:4000"
        volumes:
            - ./frontend/:/client
    database:
        image: cockroachdb/cockroach
        command: start --insecure
        expose:
         - "8080"
         - "26257"
        ports:
            - "8080:8080"
            - "26257:26257"
        volumes:
            - ./database_volume/:/cockroach/cockroach-data
    # TODO: add nginx for frontend
    # nginx:
    #     image: nginx:latest
    #     depends_on:
    #         - graphql
    #         - file
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/nginx.conf
    #     ports:
    #         - 80:80
    #         - 443:443

